config/routes.rb
Ipsorter::Application.routes.draw do

  get "sorter/format"

  get "sorter/index"

  get "sorter/sort"

  get "sorter/compare"

  post "sorter/sort"

  post "sorter/compare"

  post "sorter/format"

  root :to => 'sorter#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sorter_controller.rb
class SorterController < ApplicationController
  def index

  end

  def sort
  	# puts params[:source]
  	@result = params[:source]
  	@btn_type = params[:commit]
  	# puts @result.nil?
  	if @result.nil? ==false
  		@match = @result.scan(/\b(?:\d{1,3}\.){3}\d{1,3}\b/)
  	end
  end

  def compare
  	@result1 = params[:source1]
  	# puts @result1.nil?
  	@result2 = params[:source2]
  	# puts @result2.nil?
  	if @result1.nil? == false
  		@match1 = @result1.scan(/\b(?:\d{1,3}\.){3}\d{1,3}\b/)
  	end
  	if @result2.nil? == false
  		@match2 = @result2.scan(/\b(?:\d{1,3}\.){3}\d{1,3}\b/)
  	end

  	@comp_res = []
  	if @match1.nil? == false && @match2.nil? == false
  		
  		@match1.each do |a|
  			if @match2.include?(a)
  				@comp_res.push(a)
  			end
  		end

  		@match2.each do |a|
  			if @match1.include?(a)
  				@comp_res.push(a)
  			end
  		end

  		# puts @match1.inspect
  		# puts @match2.inspect
  		# puts @comp_res.uniq.inspect
  	end
  end

  def format
  	@result = params[:source]
  	if @result.nil? == false
  		@match = @result.scan(/\b(?:\d{1,3}\.){3}\d{1,3}\b/)
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sorter_helper.rb
module SorterHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ipsorter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sorter/compare.html.erb
<%= button_to "Home", root_path%>
<%= form_tag( :action => "compare") %>
<% if @result1.nil? == true %>
  <%= text_area_tag(:message, "Dataset #1", :size => "100x10", :id => "src1", :name => "source1" ) %>
<% else %>
  <%= text_area_tag(:message, "#{@match1.join("\n")}", :size => "100x10", :id => "src1", :name => "source1" ) %>
<% end %>
<br />
<% if @result2.nil? == true %>
  <%= text_area_tag(:message, "Dataset #2", :size => "100x10", :id => "src2", :name => "source2" ) %>
<% else %>
  <%= text_area_tag(:message, "#{@match2.join("\n")}", :size => "100x10", :id => "src2", :name => "source2" ) %>
<% end %>
<br />
Results:
<br>
<%= text_area_tag(:message, "#{@comp_res.uniq.join("\n")}", :size => "100x10", :id => "res", :name => "results" ) %>
<br />
<br />
<%= submit_tag("Compare IP sets") %>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
</script>
<script>
	$(document).ready(function(){
		$text1 = $("#src1").text();
		if ($text1 == "Dataset #1")
			{
					$("#src1").click(function(){
					$("#src1").text("");
				});
			}
			$text2 = $("#src2").text();
		if ($text2 == "Dataset #2")
			{
					$("#src2").click(function(){
					$("#src2").text("");
				});
			}
	});
</script>

app/views/sorter/format.html.erb
<%= button_to "Home", root_path %>
<%= form_tag( :action => "format") %>
<% if @result.nil? == true %>
  <%= text_area_tag(:message, "Enter IPs to format as CSV here...", :size => "100x25", :id => "src", :name => "source" ) %>
<% else %>
  <%= text_area_tag(:message, "#{@match.join(", ")}", :size => "100x25", :id => "src", :name => "source" ) %>
<% end %>
<br>
<br>
<%= submit_tag("Format as CSV") %>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
</script>
<script>
	$(document).ready(function(){
		$text = $("#src").text();
		if ($text == "Enter IPs to format as CSV here...")
			{
					$("#src").click(function(){
					$("#src").text("");
				});
			}
	});
</script>

app/views/sorter/index.html.erb
<%= link_to "Parse IPs", sorter_sort_path %> | <%= link_to "Compare IP Sets", sorter_compare_path %> | <%= link_to "CSV Format List", sorter_format_path %>

app/views/sorter/parse.html.erb
<h1>Sorter#parse</h1>
<p>Find me in app/views/sorter/parse.html.erb</p>

app/views/sorter/sort.html.erb
<%= button_to "Home", root_path %>
<%= form_tag( :action => "sort") %>
<% if @result.nil? == true %>
  <%= text_area_tag(:message, "Enter text to parse for IPs here...", :size => "100x25", :id => "src", :name => "source" ) %>
<% else %>
	<% if @btn_type == "Parse IP Addresses" %>
  		<%= text_area_tag(:message, "#{@match.join("\n")}", :size => "100x25", :id => "src", :name => "source" ) %>
	<% else %>
		<%= text_area_tag(:message, "#{@match.uniq.join("\n")}", :size => "100x25", :id => "src", :name => "source" ) %>
	<% end %>
<% end %>
<br />
<% if @match.nil? == false %>
  <%= @match.length %>
<% end %>
<br />
<br />
<%= submit_tag("Parse IP Addresses") %> <%= submit_tag("Parse Unique IP Addresses") %>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
</script>
<script>
	$(document).ready(function(){
		$text = $("#src").text();
		if ($text == "Enter text to parse for IPs here...")
			{
					$("#src").click(function(){
					$("#src").text("");
				});
			}
	});
</script>